title: Francesco Lo Sterzo
author:
  name: Francesco Lo Sterzo
  email: francescolost@gmail.com
description: My personal blog

markdown: kramdown
highlighter: rouge

permalink: /posts/:title

minima:
  social_links:
    twitter: flosterzo
    github: francescolosterzo
    stackoverflow: 10513250/francescols

plugins:
  - jemoji

theme: minima
